name = "Tractography"
uuid = "df9aafbb-e545-4464-854d-5d08b36f846c"
authors = ["romain veltz <romain.veltz@inria.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
